### ISSUE TITLE
Does not compile with elixir 0.13.1

### ISSUE THREAD

**Issue by smpallen99** [meh/elixir-socket#14]
I get the following error on new project created with elixir 0.13.1

[root@ucx50 socket_test]# mix deps.compile
* Compiling socket
Compiled lib/socket/address.ex
Compiled lib/socket/helpers.ex
Compiled lib/socket/datagram.ex
Compiled lib/socket/host.ex
== Compilation error on file lib/socket.ex ==
could not compile dependency socket, mix compile failed. You can recompile this dependency with `mix deps.compile socket` or update it with `mix deps.update socket`
** (CompileError) deps/socket/lib/socket.ex:52: URI.__struct__/0 is undefined, cannot expand struct URI
    (elixir) src/elixir_map.erl:55: :elixir_map.translate_struct/4
    (stdlib) lists.erl:1352: :lists.mapfoldl/3
    (elixir) src/elixir_clauses.erl:26: :elixir_clauses.match/3
    (elixir) src/elixir_clauses.erl:35: :elixir_clauses.clause/7
    (elixir) src/elixir_def.erl:182: :elixir_def.translate_clause/7
    (elixir) src/elixir_def.erl:171: :elixir_def.translate_definition/8
    (elixir) src/elixir_def.erl:89: :elixir_def.store_definition/9
